databases:
  - name: budget
    ipAllowList: []
    databaseName: budget_11tg
    user: budget_11tg_user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./bin/budget-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_11tg
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction